options:
  token: "MTAyNzM0MjY4NDMwMzY2NzIxMA.Gn3NPl.E3zmxE5lqejhy6KzaqL4MxdXhWdNsC5Xk4VKM4"
  indents: default indents
  policy: all
  auto reconnect: true
  bot: "ModernCraft"
  botName: ModernCraft
  
#EMBEDS	
  HelpEmbedColor: green
  LinksEmbedColor: green
  IPEmbedColor: green
  StatusEmbedColor: green
  AvatarEmbedColor: green
  ServerinfoEmbedColor: green
  UserinfoEmbedColor: green

  SuggestEmbedColor: green
  SuggestEmbedColorInvalidArgument: red
  
#MESSAGES
  NoPermission: "&c&l(!) &cYou don't have permission to execute this command."
  Usage: "&c&l(!) &cUsage: /bot <start|stop>"

  StartingBot: "&a&l[!] &aStarting bot..."
  SuccesfullyStartedBot: "&a&l[!] &aBot succesfully started."
  StoppingBot: "&c&l[!] &cStopping bot..."
  SuccesfullyStoppedBot: "&c&l[!] &cBot succesfully stopped."
  
#BOT SETTINGS
  DiscordBotPrefix: !
  DiscordBotToken: "MTAyNzM0MjY4NDMwMzY2NzIxMA.Got8ng.iVPCTFpKXufwx52LMaLpqSvoGoSykj9orKSkJg"
  DiscordBotName: "ModernCraft"
  DiscordBotPlaying: "Minecraft"
  
#LINKS
  DiscordLink: https://discord.gg/gtJDbcna9s
  YouTubeLink: https://www.youtube.com/channel/UCDn3lQVLIDFGdbmku5Hy6eQ

define new bot named "ModernCraft": 
    token: "MTAyNzM0MjY4NDMwMzY2NzIxMA.G7ytbz.65FjZLh9pdBiikJe5Hd6v0IQoN8LsvVnixUF-Y"
    intents: default intents
    
discord command playing [<text>]:
    prefixes: ?
    trigger:
        if arg-1 is not set:
            reply with "Enter a game to play!"
        else:
            set the presence of the bot named "ModernCraft" to playing "ModernCraft"
    
#Test Command
discord command test:
	prefixes: ?
	trigger:
		reply with "Test Ping!"
        
discord command rules:
  prefixes: !
  trigger:
    make embed:
    set title of embed to "ModernCraft Discord Rules"
    add field named "Be kind to other members" with value "" to embed
    add field named "Swearing is allowed, but not too excessive" with value "" to embed
    add field named "No self-promoting yourself (other servers and/or other YT channels" with value "" to embed
    add field named "No NSFW content or you'll get perma-banned" with value "" to embed
    add field named "Follow Discord Terms of Service" with value "" to embed
    add field named "No memes, because this is a creative Minecraft ideas discord server not a meme or related server" with value "" to embed
    add field named "Don't ping staff for unnecessary reasons" with value "" to embed
    add field named "Have Fun!" with value "" to embed
    set embed color of the embed to light red
    reply with last embed
        
discord command links:
    prefixes: !
    trigger:
        make embed:
            set title of embed to "ModernCraft Links"
            add field named "YouTube" with value "➦ {@YouTubeLink}" to embed
            add field named "Discord Invite" with value "➦ {@DiscordLink}" to embed
            set embed color of the embed to light red
        reply with last embed
        
command link:
    trigger:
        set {_code} to a random integer between 11111 and 99999
        set {code::%{_code}%} to player
        send "&aYour unique is %{_code}%. Run the command !link %{_code}% on our discord to link your account. This code will be deleted in 2 minutes."
        wait 2 minute
        delete {code::%{_code}%}
        
discord command link [<text>]:
    prefixes: !
    trigger:
        if arg-1 is not set:
            reply with "Syntax: !link (code)"
            stop
        if {code::%arg-1%} is not set:
            reply with "&cInvalid code"
            stop
        set {discord::%discord id of event-member%::username} to {code::%arg-1%}
        reply with "You have linked with the Minecraft account %{code::%arg-1%}%."
        delete {code::%arg-1%}